/** LLM target provider configuration */
export interface LLMTarget {
  id: string;
  name: string;
  url: string;
  capabilities: string[];
  selectors: LLMSelectors;
  quirks: LLMQuirks;
  rate_limit_ms: number;
}

/** CSS selectors for DOM interaction with an LLM provider */
export interface LLMSelectors {
  input: string;
  submit: string;
  response: string;
  streaming_indicator?: string;
  done_indicator?: string;
}

/** Provider-specific behavior configuration */
export interface LLMQuirks {
  input_type: 'textarea' | 'contenteditable' | 'prosemirror' | 'quill';
  needs_native_setter?: boolean;
  needs_exec_command?: boolean;
  streaming_attr?: string;
  stability_timeout_ms?: number;
}

/** A single research sub-task */
export interface ResearchTask {
  id: string;
  title: string;
  prompt: string;
  target_model: string;
  dependencies: string[];
  priority: number;
  status: TaskStatus;
  response_file?: string;
  error?: string;
  started_at?: string;
  completed_at?: string;
}

export type TaskStatus = 'pending' | 'queued' | 'running' | 'completed' | 'failed' | 'skipped';

/** Research plan generated by the planner */
export interface ResearchPlan {
  topic: string;
  strategy: string;
  tasks: ResearchTask[];
  synthesis_strategy: string;
  created_at: string;
}

/** A research session */
export interface Session {
  id: string;
  plan: ResearchPlan;
  status: SessionStatus;
  created_at: string;
  updated_at: string;
  completed_at?: string;
}

export type SessionStatus = 'planning' | 'approved' | 'executing' | 'executed' | 'synthesizing' | 'completed' | 'failed';

/** Execution progress event */
export interface ExecutionEvent {
  type: 'task_started' | 'task_completed' | 'task_failed' | 'session_completed' | 'session_failed';
  task_id?: string;
  session_id: string;
  message: string;
  timestamp: string;
}

/** Health check result for a single provider */
export interface HealthResult {
  target_id: string;
  status: 'healthy' | 'degraded' | 'broken';
  selectors_found: Record<string, boolean>;
  checked_at: string;
  error?: string;
}
